### ISSUE TITLE
`go build` a main package with purego with Cgo enabled might fail on Windows and Linux

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#39]
https://github.com/ebitengine/purego/blob/test/example/main.go

The test bot builds the above main package like below:

```
go build -v ./...
```

And this failed at least on Linux like this:

https://github.com/ebitengine/purego/runs/8276795548

```
# github.com/ebitengine/purego/example
2022/09/09 18:57:24 duplicated definition of symbol _cgo_init
```

I think this is a minimal reproducible case of hajimehoshi/ebiten#2313: just building a main package with purego with Cgo enabled.

**Comment by hajimehoshi** [comment]
Is importing runtime/cgo related? https://github.com/ebitengine/purego/pull/20#discussion_r950359267

**Comment by TotallyGamerJet** [comment]
Is this issue fixed with [purego#40](https://github.com/ebitengine/purego/pull/40)?

**Comment by hajimehoshi** [comment]
> Is this issue fixed with https://github.com/ebitengine/purego/pull/40?

The test doesn't pass yet, right?

**Comment by hajimehoshi** [comment]
We would need `//go:build darwin || windows` for the example.

**Comment by hajimehoshi** [comment]
My guess was that renaming `cgo.go` to `cgo_darwin.go` would solve the issue, but this doesn't solve an issue of cross-compiling on Linux. This is mysterious... https://github.com/ebitengine/purego/runs/8281533562

**Comment by TotallyGamerJet** [comment]
Yeah this seems like Go 1.15 is ignore the build tags bc that's only buildable on darwin

**Comment by hajimehoshi** [comment]
Perhaps does this happen only with arm64?

**Comment by TotallyGamerJet** [comment]
Perhaps, I'm working on getting a Linux VM to test
